Feature/ag 66 store metadata
ai-guardrails/ai-guardrails pull request #53
Opened 2023-08-29 07:31 UTC by Anna-Gomez

Added uploaded_by, uploaded_at to metadata and allowed the user to add any additional metadata to the file via the api input.

2023-08-29 15:49 UTC, CodeCrafter7 requested changes

2023-08-29 15:49 UTC, CodeCrafter7 commented on api/src/app/controller/documents_controller.py
> +    metadata = json.loads(request.form['apiMetadata']) if 'apiMetadata' in request.form else {}
@Hana-Bell @Anna-Gomez , can we please call this just "metaData" instead of "apiMetadata"

2023-08-29 15:49 UTC, CodeCrafter7 commented on api/src/app/service/chat_service.py
> +            uploaded_by = current_user_email
function parenthesis missing.

2023-08-30 04:07 UTC, Anna-Gomez commented on api/src/app/controller/documents_controller.py
> +    metadata = json.loads(request.form['apiMetadata']) if 'apiMetadata' in request.form else {}
@CodeCrafter7 changed to metaData

2023-08-30 23:10 UTC, CodeCrafter7 approved these changes

2023-08-30 23:10 UTC, merged