Updated Langchain to latest Version
ai-guardrails/ai-guardrails pull request #55
Opened 2023-08-29 12:05 UTC by Vikram-Ch14

2023-08-29 15:47 UTC, CodeCrafter7 requested changes

2023-08-29 15:47 UTC, CodeCrafter7 commented on api/Pipfile
@Vikram-Ch14 please remove the sentence-transformers = "==2.2.2" dependency from this file.
also remove the "==" from langchain version.

2023-08-29 15:47 UTC, CodeCrafter7 commented on api/Pipfile.lock
remove this file from commit

2023-08-30 04:26 UTC, Vikram-Ch14 commented on api/Pipfile.lock
Removed Pipfile.lock file

2023-08-30 04:26 UTC, Vikram-Ch14 commented on api/Pipfile
done with above changes @CodeCrafter7

2023-08-30 23:06 UTC, CodeCrafter7 approved these changes

2023-08-30 23:06 UTC, merged