Feature/acl impl datasource and conversation
ai-guardrails/ai-guardrails pull request #78
Opened 2023-09-11 11:15 UTC by uma3355

2023-09-11 20:06 UTC, CodeCrafter7 reviewed
@uma3355 Cant merge this right now because this will break the FE, the chat list will not render

2023-09-13 07:33 UTC, CodeCrafter7 requested changes

2023-09-13 07:33 UTC, CodeCrafter7 commented on api/src/app/database/models.py
> +    acl = Column(JSONB)
@uma3355 I think this is not required anymore

2023-09-13 07:33 UTC, CodeCrafter7 commented on api/src/app/database/repository.py
> +            subquery = Persistence.acl_subquery(userName, userGroups, userRoles, 'data_source', session)
@uma3355 can you please remove the print statement, also try to do a single query using a join?

2023-09-13 07:36 UTC, CodeCrafter7 commented on api/src/app/repo/db.py
> +    print(facet_stage)
@uma3355 remove print statement

2023-09-13 07:37 UTC, CodeCrafter7 requested changes

2023-09-13 07:37 UTC, CodeCrafter7 commented on api/src/app/repo/db.py
> +    print(match_query)
remove print

2023-09-14 17:40 UTC, closed without merging

2023-09-14 17:40 UTC, uma3355 commented
this code is in feature/conversation-acl-update3 branch